#!/usr/bin/env python3
"""
Regenerate the extended font library from the files in ../fonts.

For every font in fonts/ that is NOT one of the hand-curated "featured" faces,
this writes:
  - fonts/library.css   — one @font-face per file (family = "lib-<filename>")
  - fonts-data.js        — window.FONT_LIBRARY = [{name, family, cat, match}, ...]

The featured faces (Asgerion, Steak Muroh, ITC Tiffany, …) are declared by hand
in fonts/fonts.css and listed in the FONTS array in app.js, so they are skipped
here.

Usage:
    pip install fonttools
    python3 scripts/build_library.py
"""

import glob
import json
import os
import re
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS_DIR = os.path.join(HERE, "..", "fonts")
DATA_FILE = os.path.join(HERE, "..", "fonts-data.js")

# Hand-curated faces — declared in fonts/fonts.css, rendered as featured specimens.
CURATED = {
    "asgerion.otf", "asgerion-line.otf", "asgerion-solid.otf", "kids-brush.ttf",
    "millwee-manuscripting.ttf", "steak-muroh.ttf", "wonderful-combination.otf",
    "wubba-lubba-dub-dub.ttf", "get-schwifty.ttf", "rouletta.ttf",
    "adobe-garamond-bold.ttf", "care-bear-family.ttf", "complete-plain.ttf",
    "itc-tiffany-demi-italic.otf", "itc-tiffany-light.otf",
    "itc-tiffany-medium.otf", "tiffany-heavy-condensed.ttf",
}

MATCH = {
    "Mono":      ["mono", "code", "technical", "readable", "calm"],
    "Pixel":     ["display", "pixel", "quirky", "experimental", "fun", "punchy", "short"],
    "Geometric": ["display", "geometric", "bold", "poster", "headline", "logo", "short", "punchy"],
    "Georgian":  ["script", "traditional", "calligraphic", "elegant", "short"],
    "Heavy":     ["display", "bold", "heavy", "loud", "poster", "headline", "punchy", "short"],
    "Bold":      ["display", "bold", "headline", "poster", "logo", "punchy", "short"],
    "Light":     ["sans", "light", "clean", "modern", "calm", "readable"],
    "Rounded":   ["sans", "rounded", "friendly", "casual", "playful", "readable"],
    "Sans":      ["sans", "clean", "modern", "readable", "body", "neutral", "calm"],
    "Serif":     ["serif", "classic", "readable", "elegant", "calm", "body"],
    "Display":   ["display", "short", "poster", "logo", "punchy"],
}


def clean_name(full, fam):
    s = full or fam or ""
    s = re.sub(r"(?i)\s*webfont\s*", " ", s)
    s = s.replace("_", " ")
    s = re.sub(r"(?i)\bRegular\b", "", s)
    return re.sub(r"\s+", " ", s).strip() or fam


def category(name):
    f = name.lower()
    if "mono" in f: return "Mono"
    if any(k in f for k in ("dots", "bitneon", "neon")): return "Pixel"
    if any(k in f for k in ("banner", "square")): return "Geometric"
    if any(k in f for k in ("mtavruli", "nusxuri", "mkhedruli", "kolheti",
                            "lortkipanidze", "rachveli")): return "Georgian"
    if any(k in f for k in ("heavy", "black", "ultra")): return "Heavy"
    if "bold" in f: return "Bold"
    if any(k in f for k in ("light", "thin")): return "Light"
    if "rounded" in f: return "Rounded"
    if any(k in f for k in ("phone sans", "sans", "arial", "dejavu", "glaho",
                            "nino", "venuri", "ucnobi")): return "Sans"
    if any(k in f for k in ("nostalgia", "rioni", "algeti", "classic",
                            "irubaqidze", "mikheil", "nuskha")): return "Serif"
    return "Display"


def main():
    files = sorted(glob.glob(os.path.join(FONTS_DIR, "*.ttf")) +
                   glob.glob(os.path.join(FONTS_DIR, "*.otf")))
    faces, data = [], []
    for path in files:
        fn = os.path.basename(path)
        if fn in CURATED:
            continue
        stem, ext = os.path.splitext(fn)
        fmt = "opentype" if ext.lower() == ".otf" else "truetype"
        try:
            n = TTFont(path, lazy=True)["name"]
            full, fam = n.getDebugName(4), n.getDebugName(1)
        except Exception:
            full = fam = stem
        family = "lib-" + stem
        name = clean_name(full, fam)
        cat = category(name)
        faces.append(
            f'@font-face{{font-family:"{family}";'
            f'src:url("./{fn}") format("{fmt}");font-display:swap;}}')
        data.append({"name": name, "family": family, "cat": cat, "match": MATCH[cat]})

    with open(os.path.join(FONTS_DIR, "library.css"), "w") as fh:
        fh.write("/* Auto-generated by scripts/build_library.py. Do not hand-edit. */\n")
        fh.write("\n".join(faces) + "\n")

    with open(DATA_FILE, "w") as fh:
        fh.write("/* Auto-generated by scripts/build_library.py. Do not hand-edit. */\n")
        fh.write("window.FONT_LIBRARY = " +
                 json.dumps(data, ensure_ascii=False, indent=0) + ";\n")

    print(f"Wrote {len(faces)} library faces "
          f"(skipped {len(CURATED)} curated). -> fonts/library.css, fonts-data.js")


if __name__ == "__main__":
    main()
